version: '3.8'

services:
  ecn-fix-server:
    build:
      context: ../
      dockerfile: ecngateway/backend/Dockerfile
    container_name: ecngateway
    # ports:
    #   - "9898:9898" # Exposed via HAProxy
    environment:
      - REDIS_HOST=fintech_redis
      - REDIS_PORT=6379
      - KAFKA_BOOTSTRAP_SERVERS=fintech_redpanda:9092
      # Assuming Redpanda/Kafka is running on host port 9092.
      # If using Redpanda in another container, use its service name.
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend/log:/app/log
      - ./backend/store:/app/store
    networks:
      - default
      - fintech_net

  ecn-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ecn-ui
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "3005:3000"
    networks:
      - default

  ecn-api:
    build:
      context: ../
      dockerfile: ecngateway/backend/Dockerfile
    container_name: ecn-api
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=fintech_redis
      - REDIS_PORT=6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/app
    networks:
      - default
      - fintech_net

networks:
  fintech_net:
    external: true
    name: tradingserver_backbone_net
