version: "3.8"

services:
  exchange-engine:
    build: 
      context: ../
      dockerfile: exchange/backend/Dockerfile
    container_name: exchange
    environment:
      - REDIS_HOST=fintech_redis
      - REDIS_PORT=6379
      - KAFKA_BOOTSTRAP_SERVERS=fintech_redpanda:9092
      - KAFKA_TOPIC_EXECUTION_REPORTS=execution_reports
      - LOG_LEVEL=INFO
    networks:
      - infrastructure_fintech-net
    # depends_on:
    #   - infrastructure_fintech-redis
    #   - infrastructure_fintech-redpanda
    restart: always
    command: python main.py

  exchange-api:
    build: 
      context: ../
      dockerfile: exchange/backend/Dockerfile
    container_name: exchange-api
    command: uvicorn api:app --host 0.0.0.0 --port 8002
    environment:
      - REDIS_HOST=fintech_redis
      - REDIS_PORT=6379
    ports:
      - "8002:8002"
    networks:
      - infrastructure_fintech-net
    depends_on:
      - exchange-engine
    restart: always

  exchange-ui:
    build: 
      context: ../
      dockerfile: exchange/ui/Dockerfile
    container_name: exchange-ui
    ports:
      - "3003:3003"
    networks:
      - infrastructure_fintech-net
    depends_on:
      - exchange-api
    restart: always

networks:
  infrastructure_fintech-net:
    external: true
    name: tradingserver_backbone_net
