services:
  exchange-engine:
    build: 
      context: ../
      dockerfile: exchange/backend/Dockerfile
    container_name: exchange-engine
    environment:
      - REDIS_HOST=fintech_redis
      - REDIS_PORT=6379
      - KAFKA_BOOTSTRAP_SERVERS=fintech_redpanda:9092
      - KAFKA_TOPIC_EXECUTION_REPORTS=execution_reports
      - LOG_LEVEL=INFO
    networks:
      - tradingserver-net
      - fintech_net
    volumes:
      - ./backend:/app
      - ../packages/py-core:/tmp/py-core
    restart: always
    command: python main.py

  exchange-api:
    build: 
      context: ../
      dockerfile: exchange/backend/Dockerfile
    container_name: exchange-api
    command: uvicorn api:app --host 0.0.0.0 --port 8002 --reload
    environment:
      - REDIS_HOST=fintech_redis
      - REDIS_PORT=6379
    ports:
      - "8002:8002"
    networks:
      - tradingserver-net
      - fintech_net
    volumes:
      - ./backend:/app
      - ../packages/py-core:/tmp/py-core
    depends_on:
      - exchange-engine
    restart: always

  exchange-ui:
    build: 
      context: ../
      dockerfile: exchange/ui/Dockerfile
    container_name: exchange-ui
    ports:
      - "3003:3003"
    volumes:
      - ./ui:/src/exchange/ui
      - /src/exchange/ui/node_modules
      - ../packages/ui-core:/src/packages/ui-core
    environment:
      - VITE_WS_URL=ws://localhost:8002/ws
    networks:
      - tradingserver-net
      - fintech_net
    depends_on:
      - exchange-api
    restart: always

networks:
  tradingserver-net:
    driver: bridge
  fintech_net:
    external: true
    name: tradingserver_backbone_net
